apiVersion: v1
kind: Secret
metadata:
  name: document-analyzer-secrets
  namespace: document-analyzer
type: Opaque
stringData:
  # Local development settings - To be filled in by variables in CICD or from secret store integration
  AZURE_FUNCTIONS_ENVIRONMENT: Development
  COSMOSDB_CONNECTION: "AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="
  AZURE_OPENAI_ENDPOINT: "https://dummy-openai.openai.azure.com/"
  AZURE_OPENAI_API_KEY: "dummy-key-replace-in-production"
  APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=00000000-0000-0000-0000-000000000000"
  # Frontend environment variables
  REACT_APP_AZURE_CLIENT_ID: "00000000-0000-0000-0000-000000000000"
  REACT_APP_AZURE_AUTHORITY: "https://login.microsoftonline.com/common"
