apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: document-analyzer-backend-pvc
  namespace: document-analyzer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
